### PR TITLE
WIP: Member pages

### LINKED ISSUE #27: Member Page
At least get some basic layout/data format stuff going + update the readme on how to either:

1. Make a PR
2. Make an issue to update it

^ Not everyone is savvy with Git, or has the time to learn it + github, so accessibility would be nice IMO.

### PR DESCRIPTION
**Pull request by StrangeWill**
Awaiting site layout tweaks before adding styles

DO NOT MERGE YET ZOMG

_Partially_ resolves #27

### CODE REVIEW

**Comment by agarzola** [comment]
Let’s add `homepage_ok` (or something like it) to the list of allowed properties and explain that if that is set to true (or a truthy value), a user’s gravatar and profile info will be used (at random) on the home page quilt thing (whenever that is implemented). Probably a good idea to make it painfully obvious that this is strictly opt in.

**Comment by agarzola** [comment]
I get this error running after adding a new user to the `_data/members/` directory:

```
Liquid Exception: no implicit conversion of String into Integer in _pages/members.html
```

**Comment by StrangeWill** [comment]
@agarzola yeah, my bad. Jekyll doesn't allow me to do that using the `_data` dir, had to use collections, I snagged a plugin that allows us to group collections so I converted members to collections and stuck them under `./_collections/members`. Should work now. 👍

**Comment by agarzola** [comment]
It's weird, though. Yesterday I implemented the homepage quilt feature with similar logic to the one found in this members page, and all I did was add a couple more member files. Didn't cause any issues for me then.

**Comment by agarzola** [comment]
The single-commit pull request I just submitted to @StrangeWill’s repo fixes the only IE issue I found via BrowserStack. After that gets merged into his repo, I’m confident this PR can get merged to master.

**Comment by brb3** [comment]
Holy crap! This is fantastic!
I'm merging this in so that I can make a PR to slap my mug up there 😃

**Pull request merged**
