### PR TITLE
Nav groups

### PR DESCRIPTION
**Pull request by agarzola**
Implements idea discussed in #37.

Navigation is now grouped into two groups.

### CODE REVIEW

**Comment by agarzola** [comment]
**Don’t merge this just yet.** Major bug.

**Comment by agarzola** [comment]
All good now. Ready for review.

**Comment by StrangeWill** [comment]
image
When I open the menu it gets all screwed up, also can't close the menu again (not sure if that's a problem)

**Comment by agarzola** [comment]
What browser is this on?

**Comment by StrangeWill** [comment]
Chrome

**Comment by agarzola** [comment]
Now it looks like that in my Chrome. Sooo weird that it didn’t do that before… I’m on it.

**Comment by agarzola** [comment]
So the issue seems to be tied to a missing _Channels_ page. Add a _Channels_ page and the issue clears itself right up. That being said, this is not expected behavior at all, so I’ll continue looking into it.

**Comment by agarzola** [comment]
That fixes it. Kind of a funny problem: without the _channels_ page, the first page that gets picked up is the _coc_, which is `menu_group: 2`. So when I grouped the pages by that property, `2` is the first key in that hash, then `1`. So naturally, items belonging to group 2 are inserted into the markup first.

Anyhow, it’s ready for review once again.

**Comment by StrangeWill** [comment]
Works for me :shipit:

**Comment by brb3** [comment]
Looks good. I'll merge it now.

**Pull request merged**
