### PR TITLE
WIP: First stab at home page (about) content

### LINKED ISSUE #5: Create an about page
The home page should serve as an "about" page. Need some basic copy written to explain what devanooga is, why it exists.

### PR DESCRIPTION
**Pull request by agarzola**
Fixes #5 *Not ready to merge yet.*

Would like some feedback on this copy. Also, where would we link the _Get in touch with us_ bit in the About section? Are we gonna have a contact page with a form and/or contact details, or should we change the language to direct people to our Slack community?

I’d like for there to be a way for folks to get in touch outside of Slack, but I also realize that creates Yet Another Noise Channel for whoever will receive notifications for that (email, contact form submissions, whatever). Maybe a contact form that uses a webhook to post submissions to a private Slack channel?

### CODE REVIEW

**Comment by agarzola** [comment]
Also just realized @brb3 had assigned issue #5 to himself. Sorry to step on your toes, man.

**Comment by StrangeWill** [comment]
We can look into using a contact form using Netlify's built in system (see my comment here: https://github.com/devanooga/devanooga.github.io/issues/1#issuecomment-275829022). I think that'll be good enough for a generic "contact us" page (will have to see if we get notified on responses or what).

While Slack is a main method of communication with us online -- I'd lean heavily on an easy way to reach out to us outside of Slack (eg: if a user is having trouble getting on Slack, asking us on Slack isn't helpful, or in the extreme case of someone not logging into Slack to avoid someone, they still should be able to talk to us).

**Comment by StrangeWill** [comment]
As far as content goes, good start. I'd love to see something visual (CC licensed image of Chattanooga or something?), but I think the content is great for now.

**Comment by agarzola** [comment]
I want to stay away from using a photo of the city. That’s kind of the go-to hero image for local community websites that want an image on the home page and don’t want to think too hard about it. The community is about the people, which we don’t (yet) have a picture of. I’m not against using images, but I’m also not against having a text-only home page for the time being if we can’t come up with an image that adds value to the content. Does that make sense?

---

That being said, it’d be great to create a tiled wall of little gravatars, once we have enough members signed up and added to the site with their gravatars and such. We could even write a little plugin that feeds the template a randomized array of image urls (tied to member names), which the home page template can use to create a quilt of square little member images. If we do something like that, I’d make it opt-in. Whatever method we come up with for people to add themselves to the site should include an optional `home_page_ok` setting (or something like it) confirming that this person doesn’t mind being in the pool of people we use for the “quilt.”

**Comment by StrangeWill** [comment]
@agarzola to be entirely fair: you've been kicking butt on design aspects so I'll just defer to you that the text is fine for the time being -- _ideally_ yeah I'd like a images of the community too, not sure when we'll get a nice one done though.

---

I like the quilt idea 👍

**Comment by brb3** [comment]
@agarzola the copy is solid. Once we have the community kind of fleshed out we can revisit.

Also, I _really_ dig the "quilt" idea. That sounds cool. I'm fine with merging this whenever you are ready, then we can add the quilt piece once we start on the members section.

**Comment by agarzola** [comment]
I’ll give the copy a once-over and push any tweaks. I’ll also link the _Get in touch with us_ line to… `/contact/`? `admin@devanooga.com`?

I’ll post here when it’s ready.

**Comment by brb3** [comment]
@agarzola I guess just a `mailto:admin@devanooga.com` for now is fine.

I'm going to look into what we can do in terms of email. It would probably make sense for a few of us to have access to this admin email account.

**Comment by agarzola** [comment]
This is ready to merge, but be aware that now we link to a `/contact` page that doesn’t exist.

**Comment by brb3** [comment]
@agarzola ok, I'll go ahead and merge then. I made an issue for the contact page #26

**Pull request merged**
